name: tthgnn_qif
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - numpy=2.0.1
  - pandas=2.3.3
  - scipy=1.13.1
  - scikit-learn=1.6.1
  - networkx=3.2.1
  - pyyaml=6.0.2
  - tqdm=4.67.1
  - matplotlib=3.9.2
  - joblib=1.4.2
  - pip
